# human should be able to read 200 chars per line
Layout/LineLength:
  Max: 200

# relax branch condition size, code can be too verbose
Metrics/AbcSize:
  Max: 40

# short clear method name 
Metrics/MethodLength:
  Max: 25

# no performance implication
Style/OptionalBooleanParameter:
  Enabled: false

# %i(array) is not common in Ruby
Style/SymbolArray:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'serpapi.gemspec'
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
    - 'script/*'
    - 'oobt/*'
    - 'Gemfile'
    - 'Rakefile'