Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 21

Metrics/MethodLength:
  Max: 25

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

AllCops:
  Exclude:
    - 'serpapi.gemspec'
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
    - 'script/*'
    - 'Gemfile'
    - 'Rakefile'