name: serpapi-ruby 
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.1.2, 2.6.9, 2.7.6]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: lint
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: bundle exec rake lint
    - name: tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: bundle exec rake test
    # oobt does not work with ruby 2.2
    #- name: oobt
    #  env:
    #    API_KEY: ${{ secrets.API_KEY }}
    #  run: make oobt
