# alternative ruby implementation
name: serpapi-ruby-alternative
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 'truffleruby' - git action is broken
        ruby-version: [ 'jruby', 'truffleruby+graalvm']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: oobt
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: bundle exec rake oobt
