name: serpapi-ruby 
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # '1.9.3' - gem dependency issue: https://github.com/serpapi/serpapi-ruby/actions/runs/4631801001/jobs/8195101031
        # 'truffleruby' - git action is broken
        # '2.0.0', rubocop broken
        ruby-version: [ '2.1.9', '2.2', '3.1', '2.6', 'jruby', 'truffleruby+graalvm']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: lint
        run: bundle exec rake lint
      - name: tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: bundle exec rake test
      - name: oobt
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: bundle exec rake oobt